[package]
name = "aoc_driver"
version = "0.2.2"
edition = "2021"
description = "helper macros and functions for AoC"
repository = "https://github.com/Ben-Lichtman/aoc_driver"
license = "MIT OR Apache-2.0"

[dependencies]
thiserror = "1.0.37"
ureq = "2.5.0"
