[package]
name = "aoc_macros"
version = "0.1.0"
edition = "2021"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.32"
quote = "1.0.10"
serde = { version = "1.0.130", features = ["derive"] }
syn = { version = "1.0.81", features = ["full", "extra-traits"] }
toml = "0.5.8"
