[package]
name = "aoc_driver"
version = "0.1.5"
edition = "2021"
description = "helper macros and functions for AoC"
repository = "https://github.com/Ben-Lichtman/aoc_driver"
license = "MIT OR Apache-2.0"

[dependencies]
aoc_macros = { version = "0.1.5", path = "../aoc_macros" }
ureq = "2.3.1"